### ISSUE TITLE
Faucet - Request funds wording

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/faucet-web#229]
As a user of the faucet, I want to have user friendly wording, so that I can better interact with the interface

Given I am in https://faucet.okp4.network/
When I want to request funds by using a chain address 
Then I want the wording in the section to be :

> Request funds with OKP4 chain address
> 0xxxxxxxxxxxxxxxxxxxxxxxxxxx

![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/20daf508-c4a5-462a-80af-72830fe9de3b)

Example : ![image.png](https://images.zenhubusercontent.com/642d29f6f41891784a960ff2/025eb2be-19c7-4b1b-9282-1d82518a3e2a)

**Comment by ChaimaaZaoui** [comment]
To release at the same time as the recaptcha

**Comment by ErikssonJoakim** [comment]
@ChaimaaZaoui the faucet is internationalized in english and french so we need a french description as well. Are you ok with: `Demander des fonds avec une adresse de la chaine OKP4` ?

**Comment by ChaimaaZaoui** [comment]
ça me convient merci

**Comment by ccamel** [comment]
@ChaimaaZaoui @ErikssonJoakim The placeholder is not correct for the expected format of okp4 addresses. We should use `okp4xxxx...`:

<img width="432" alt="image" src="https://github.com/okp4/faucet-web/assets/9574336/d6224e0b-0cee-4efa-a243-ce3b12f1ee89">

**Comment by MdechampG** [comment]
Test 20/06 OK ✅
